---
basic_package : - 'wget'
                - 'openssh-clients'
                - 'mc'
                - 'vim-common'
                - 'git'
                - 'tmux'
                - 'iptables'
                - 'ruby'
                - 'ruby-devel'
                - 'rubygems'
basic_erase_package : -
vagrant_box_package :   - 'gcc'
                        - 'gcc-c++'
                        - 'kernel-devel'
                        - 'make'
                        - 'bzip2'
                        - 'curl'
gem_package : - 'puppet-lint'
